# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Eliza Danila
tagline:          'Portfolio'
description:      'An honors computer science student at MTSU.'
url:              https://eliza-danila.github.io/
baseurl:          /

author:
  name:           'Eliza Danila'
  url:            https://www.linkedin.com/in/eliza-danila-8bb984246/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Eliza-Danila/Eliza-Danila.github.io

plugins:
  - jekyll-paginate
